version: '3.9'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/server
    depends_on:
      - mysql
    links:
      - mysql
  mysql: 
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=PS_VidyaCode
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app
  front:
    container_name: front
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - server
    links:
      - server